version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  stalkerchan:
    image: locmai/stalkerchan
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ${PWD}/config.yaml:/deploy/config.yaml
volumes:
  db:
