name: CI

env:
  CARGO_TERM_COLOR: always
  MSRV: '1.60'

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
jobs:
  check-rust:
    name: rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: beta
        override: true
        profile: minimal
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: |
        cargo clippy --all --all-targets --all-features
    - name: rustfmt
      run: |
        cargo fmt --all -- --check
  check-pr:
    name: validate PR title
    runs-on: [ubuntu-latest]
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
